FROM python:3.11

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    gfortran \
    libopenblas-dev \
    liblapack-dev \
    pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Debug check
RUN which gfortran && gfortran --version

# Set work directory
WORKDIR /app

# Copy files
COPY . /app

# Install Python deps
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --prefer-binary -r requirements.txt

# Expose Flask port
EXPOSE 8000

# Start app with gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]
